name: Manual Workflow with Two Required Approvals

on:
  # Triggered manually from the Actions tab
  workflow_dispatch:
    inputs:
      company_code:
        description: "Company Code"
        required: true
      env:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  request-approval:
    name: "Approve Delete Operation for ${{ github.event.inputs.company_code }} in ${{ github.event.inputs.env }}"
    runs-on: ubuntu-latest
    # Using the production environment with required reviewers
    environment:
      name: production
    steps:
      - name: Approval Check
        run: echo "Delete operation for company code ${{ github.event.inputs.company_code }} in ${{ github.event.inputs.env }} environment has been approved by required reviewers"
        
  # deploy:
  #   name: "Delete Company ${{ github.event.inputs.company_code }} in ${{ github.event.inputs.env }}"
  #   needs: request-approval
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - name: Set up environment
  #       run: |
  #         echo "Setting up for delete operation"
  #         echo "Company Code: ${{ github.event.inputs.company_code }}"
  #         echo "Environment: ${{ github.event.inputs.env }}"
          
  #     - name: Execute Delete Operation
  #       run: |
  #         echo "Executing delete operation for Company Code: ${{ github.event.inputs.company_code }} in ${{ github.event.inputs.env }} environment"
  #         # Add your actual deletion commands here