name: Manual Workflow with Approval

permissions:
  issues: write
  contents: read


on:
  workflow_dispatch:
    inputs:
      company_code:
        description: 'Company Code'
        required: true
        type: string
      env:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  approval:
    name: "Delete: Company Code ${{ github.event.inputs.company_code }}, Environment ${{ github.event.inputs.env }}"
    runs-on: ubuntu-latest
    steps:
      - name: Pending approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: gouravsaini025,adayush
          minimum-approvals: 2
          issue-title: "[CRITICAL] Infrastructure Cleanup Approval Required for ${{ github.event.inputs.company_code }}"
          issue-body: "⚠️ **Infrastructure Deletion Request**\n\nPlease review and approve/deny the following infrastructure cleanup:\n\n**Details:**\n- **Company Code**: `${{ github.event.inputs.company_code }}`\n- **Environment**: `${{ github.event.inputs.env }}`\n- **Requested by**: `${{ github.actor }}`\n\n⚡ **Note**: This action will permanently delete infrastructure resources.\nPlease verify the details carefully before approving."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'approve,approved,lgtm,yes'
          additional-denied-words: 'deny,denied,no'
          
  main-job:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Your actual workflow steps here
      - name: Run after approval
        run: echo "Workflow was approved and is now running!"