name: Validate and Deploy

on:
  workflow_dispatch:
    inputs:
      company_code:
        description: 'Company Code'
        required: true
      env:
        description: 'Environment (dev/stage/prod)'
        required: true
        default: 'dev'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Validate company code for production
        if: ${{ inputs.env == 'prod' }}
        run: |
          # Display confirmation message
          echo "::notice::⚠️ PRODUCTION DEPLOYMENT for company code ${{ inputs.company_code }} ⚠️"
          
      - name: Create confirmation file
        if: ${{ inputs.env == 'prod' }}
        run: |
          echo "Company code: ${{ inputs.company_code }}" > confirmation.txt
          echo "Environment: ${{ inputs.env }}" >> confirmation.txt
      
      - name: Upload confirmation for review
        if: ${{ inputs.env == 'prod' }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: deployment-confirmation
          path: confirmation.txt

  confirm-and-deploy:
    needs: validate
    if: ${{ github.event.inputs.env == 'prod' }}
    environment:
      name: production
      # URL to the deployment (optional)
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Download confirmation
        uses: actions/download-artifact@v3.0.2
        with:
          name: deployment-confirmation
      
      - name: Display confirmation
        run: |
          echo "⚠️ PRODUCTION DEPLOYMENT CONFIRMATION ⚠️"
          cat confirmation.txt
          echo "Proceeding with deployment for company code ${{ github.event.inputs.company_code }} to PRODUCTION"
      
      - name: Deploy to production
        run: |
          echo "Deploying to production for company ${{ github.event.inputs.company_code }}"
          # Your deployment steps here