name: reload

on:
  workflow_dispatch:
    inputs:
      # sprint_name:
      #   description: "Sprint Version"
      #   required: true
      # company_code:
      #   description: "Company Code"
      #   required: true
      env:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod
          - preprod
jobs:
  sharpsell:
    name: testing-sharpsell
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        id: set_env_var
        run: |
          echo "MY_ENV_VAR=myValue" >> $GITHUB_OUTPUT
          
      - name: Use environment variable
        id: use_env_var
        run: |
          x=${{ steps.set_env_var.outputs.MY_ENV_VAR }}
          echo "$x"
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
          echo "is_error=false" >> $GITHUB_OUTPUT
      
      - name: "Exit with failure if status != SUCCEEDED"
        if: steps.set_env_var.outputs.MY_ENV_VAR != 'myValue' || steps.use_env_var.outputs.is_error == 'true'
        run: exit 1
