name: reload

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: "provide aws instance name"
        required: true
        type: string
      env:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod
          - preprod
jobs:
  sharpsell:
    name: testing-sharpsell
    runs-on: ubuntu-latest
    steps:
      - name: check_instance_name
        id: check_instance_name
        run: |
          # Input from the workflow_dispatch
          echo "Raw input: ${{ github.event.inputs.instance_name }}"

          # Splitting the input into an array
          IFS=',' read -r -a instance_array <<< "${{ github.event.inputs.instance_name }}"
          
          found=false
          # Print each instance name for debugging
          echo "Parsed instance names:"
          for instance in "${instance_array[@]}"; do
            echo "Instance: $instance"
            
            if [[ "$instance" != *"preprod"* ]] || [[ "$instance" != *"dev"* ]]; then
              found=true
              echo "found is true $instance"
              exit 1
            fi
          done
          
      - name: Set environment variable
        id: set_env_var
        run: |
          echo "MY_ENV_VAR=myValue" >> $GITHUB_OUTPUT
          
      - name: Use environment variable
        id: use_env_var
        run: |
          x=${{ steps.set_env_var.outputs.MY_ENV_VAR }}
          echo "$x"
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
          echo "is_error=false" >> $GITHUB_OUTPUT
      
      - name: "Exit with failure if status != SUCCEEDED"
        if: steps.set_env_var.outputs.MY_ENV_VAR != 'myValue' || steps.use_env_var.outputs.is_error == 'true'
        run: exit 1
