name: reload

on: workflow_dispatch

jobs:
  sharpsell:
    name: testing-sharpsell
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        id: set_env_var
        run: echo "MY_ENV_VAR=myValue" >> $GITHUB_OUTPUT

      - name: Use environment variable
        id: use_env_var
        run: |
          x=${{ steps.set_env_var.outputs.MY_ENV_VAR }}
          echo "$x"
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
